spring.application.name=${SPRING_APPLICATION_NAME:LAMENTACIONES-USER-MANAGEMENT}


spring.rabbitmq.host=${RABBITMQ_HOST:yak.lmq.cloudamqp.com}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:mkqpekbi}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:ZbiyBjraVzdd4oCfwxYeOlsBwhFB2NDx}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:mkqpekbi}

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://JuanCaballero:Isabella2004@clustersirha.pc6me39.mongodb.net/ClubFight?retryWrites=true&w=majority&appName=LAMENTACIONES-BACK}

jwt.secret=${JWT_SECRET:ARSW_SECRET_OSCAR_JUAN_SANTIAGO_GAME_CLUB_FIGHT_2026_SECURITY_KEY_}
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.refreshExpiration=${JWT_REFRESH_EXPIRATION:86400000}

google.client.id=${GOOGLE_CLIENT_ID:345044710231-2i6s7nu060ath19helab9g27ul2p043g.apps.googleusercontent.com}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

spring.data.redis.host=${REDIS_HOST:}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}


