spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.ssl.enabled=false

spring.data.mongodb.uri=mongodb://localhost:27017/ClubFightTest

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

jwt.secret=TEST_SECRET_KEY_ONLY_FOR_UNIT_TESTS_NOT_PRODUCTION
jwt.expiration=3600000
google.client.id=test-client-id